version: "3.7"

services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
  api-prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo
    working_dir: /play-helper-nest
    ports:
      - "3000:3000"
    env_file:
      - .env
