name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: ./docker-init.sh
      - run: docker-compose -f "docker-compose.prod.yml" up -d --build
      - run: docker-compose exec api npm run test:e2e
